package com.app.bzpower.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.realname
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.age
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.post
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String post;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.jobnumber
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String jobnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.voltage
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String voltage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.transformsub
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String transformsub;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.Administrators
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String administrators;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.remarks
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.lockname
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	private String lockname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.realname
	 * @return  the value of user.realname
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.realname
	 * @param realname  the value for user.realname
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.post
	 * @return  the value of user.post
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getPost() {
		return post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.post
	 * @param post  the value for user.post
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setPost(String post) {
		this.post = post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.jobnumber
	 * @return  the value of user.jobnumber
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getJobnumber() {
		return jobnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.jobnumber
	 * @param jobnumber  the value for user.jobnumber
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setJobnumber(String jobnumber) {
		this.jobnumber = jobnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.voltage
	 * @return  the value of user.voltage
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getVoltage() {
		return voltage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.voltage
	 * @param voltage  the value for user.voltage
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setVoltage(String voltage) {
		this.voltage = voltage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.transformsub
	 * @return  the value of user.transformsub
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getTransformsub() {
		return transformsub;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.transformsub
	 * @param transformsub  the value for user.transformsub
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setTransformsub(String transformsub) {
		this.transformsub = transformsub;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.Administrators
	 * @return  the value of user.Administrators
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getAdministrators() {
		return administrators;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.Administrators
	 * @param administrators  the value for user.Administrators
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setAdministrators(String administrators) {
		this.administrators = administrators;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.remarks
	 * @return  the value of user.remarks
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.remarks
	 * @param remarks  the value for user.remarks
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lockname
	 * @return  the value of user.lockname
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getLockname() {
		return lockname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lockname
	 * @param lockname  the value for user.lockname
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setLockname(String lockname) {
		this.lockname = lockname;
	}
}