package com.app.bzpower.entity;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andRealnameIsNull() {
			addCriterion("realname is null");
			return (Criteria) this;
		}

		public Criteria andRealnameIsNotNull() {
			addCriterion("realname is not null");
			return (Criteria) this;
		}

		public Criteria andRealnameEqualTo(String value) {
			addCriterion("realname =", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotEqualTo(String value) {
			addCriterion("realname <>", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameGreaterThan(String value) {
			addCriterion("realname >", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameGreaterThanOrEqualTo(String value) {
			addCriterion("realname >=", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameLessThan(String value) {
			addCriterion("realname <", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameLessThanOrEqualTo(String value) {
			addCriterion("realname <=", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameLike(String value) {
			addCriterion("realname like", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotLike(String value) {
			addCriterion("realname not like", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameIn(List<String> values) {
			addCriterion("realname in", values, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotIn(List<String> values) {
			addCriterion("realname not in", values, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameBetween(String value1, String value2) {
			addCriterion("realname between", value1, value2, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotBetween(String value1, String value2) {
			addCriterion("realname not between", value1, value2, "realname");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(String value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(String value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(String value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(String value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(String value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(String value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLike(String value) {
			addCriterion("gender like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotLike(String value) {
			addCriterion("gender not like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<String> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<String> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(String value1, String value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(String value1, String value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(Integer value) {
			addCriterion("age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(Integer value) {
			addCriterion("age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(Integer value) {
			addCriterion("age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(Integer value) {
			addCriterion("age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(Integer value) {
			addCriterion("age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<Integer> values) {
			addCriterion("age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<Integer> values) {
			addCriterion("age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(Integer value1, Integer value2) {
			addCriterion("age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andPostIsNull() {
			addCriterion("post is null");
			return (Criteria) this;
		}

		public Criteria andPostIsNotNull() {
			addCriterion("post is not null");
			return (Criteria) this;
		}

		public Criteria andPostEqualTo(String value) {
			addCriterion("post =", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotEqualTo(String value) {
			addCriterion("post <>", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostGreaterThan(String value) {
			addCriterion("post >", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostGreaterThanOrEqualTo(String value) {
			addCriterion("post >=", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostLessThan(String value) {
			addCriterion("post <", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostLessThanOrEqualTo(String value) {
			addCriterion("post <=", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostLike(String value) {
			addCriterion("post like", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotLike(String value) {
			addCriterion("post not like", value, "post");
			return (Criteria) this;
		}

		public Criteria andPostIn(List<String> values) {
			addCriterion("post in", values, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotIn(List<String> values) {
			addCriterion("post not in", values, "post");
			return (Criteria) this;
		}

		public Criteria andPostBetween(String value1, String value2) {
			addCriterion("post between", value1, value2, "post");
			return (Criteria) this;
		}

		public Criteria andPostNotBetween(String value1, String value2) {
			addCriterion("post not between", value1, value2, "post");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andJobnumberIsNull() {
			addCriterion("jobnumber is null");
			return (Criteria) this;
		}

		public Criteria andJobnumberIsNotNull() {
			addCriterion("jobnumber is not null");
			return (Criteria) this;
		}

		public Criteria andJobnumberEqualTo(String value) {
			addCriterion("jobnumber =", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberNotEqualTo(String value) {
			addCriterion("jobnumber <>", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberGreaterThan(String value) {
			addCriterion("jobnumber >", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberGreaterThanOrEqualTo(String value) {
			addCriterion("jobnumber >=", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberLessThan(String value) {
			addCriterion("jobnumber <", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberLessThanOrEqualTo(String value) {
			addCriterion("jobnumber <=", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberLike(String value) {
			addCriterion("jobnumber like", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberNotLike(String value) {
			addCriterion("jobnumber not like", value, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberIn(List<String> values) {
			addCriterion("jobnumber in", values, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberNotIn(List<String> values) {
			addCriterion("jobnumber not in", values, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberBetween(String value1, String value2) {
			addCriterion("jobnumber between", value1, value2, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andJobnumberNotBetween(String value1, String value2) {
			addCriterion("jobnumber not between", value1, value2, "jobnumber");
			return (Criteria) this;
		}

		public Criteria andVoltageIsNull() {
			addCriterion("voltage is null");
			return (Criteria) this;
		}

		public Criteria andVoltageIsNotNull() {
			addCriterion("voltage is not null");
			return (Criteria) this;
		}

		public Criteria andVoltageEqualTo(String value) {
			addCriterion("voltage =", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageNotEqualTo(String value) {
			addCriterion("voltage <>", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageGreaterThan(String value) {
			addCriterion("voltage >", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageGreaterThanOrEqualTo(String value) {
			addCriterion("voltage >=", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageLessThan(String value) {
			addCriterion("voltage <", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageLessThanOrEqualTo(String value) {
			addCriterion("voltage <=", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageLike(String value) {
			addCriterion("voltage like", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageNotLike(String value) {
			addCriterion("voltage not like", value, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageIn(List<String> values) {
			addCriterion("voltage in", values, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageNotIn(List<String> values) {
			addCriterion("voltage not in", values, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageBetween(String value1, String value2) {
			addCriterion("voltage between", value1, value2, "voltage");
			return (Criteria) this;
		}

		public Criteria andVoltageNotBetween(String value1, String value2) {
			addCriterion("voltage not between", value1, value2, "voltage");
			return (Criteria) this;
		}

		public Criteria andTransformsubIsNull() {
			addCriterion("transformsub is null");
			return (Criteria) this;
		}

		public Criteria andTransformsubIsNotNull() {
			addCriterion("transformsub is not null");
			return (Criteria) this;
		}

		public Criteria andTransformsubEqualTo(String value) {
			addCriterion("transformsub =", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubNotEqualTo(String value) {
			addCriterion("transformsub <>", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubGreaterThan(String value) {
			addCriterion("transformsub >", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubGreaterThanOrEqualTo(String value) {
			addCriterion("transformsub >=", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubLessThan(String value) {
			addCriterion("transformsub <", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubLessThanOrEqualTo(String value) {
			addCriterion("transformsub <=", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubLike(String value) {
			addCriterion("transformsub like", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubNotLike(String value) {
			addCriterion("transformsub not like", value, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubIn(List<String> values) {
			addCriterion("transformsub in", values, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubNotIn(List<String> values) {
			addCriterion("transformsub not in", values, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubBetween(String value1, String value2) {
			addCriterion("transformsub between", value1, value2, "transformsub");
			return (Criteria) this;
		}

		public Criteria andTransformsubNotBetween(String value1, String value2) {
			addCriterion("transformsub not between", value1, value2, "transformsub");
			return (Criteria) this;
		}

		public Criteria andAdministratorsIsNull() {
			addCriterion("Administrators is null");
			return (Criteria) this;
		}

		public Criteria andAdministratorsIsNotNull() {
			addCriterion("Administrators is not null");
			return (Criteria) this;
		}

		public Criteria andAdministratorsEqualTo(String value) {
			addCriterion("Administrators =", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsNotEqualTo(String value) {
			addCriterion("Administrators <>", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsGreaterThan(String value) {
			addCriterion("Administrators >", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsGreaterThanOrEqualTo(String value) {
			addCriterion("Administrators >=", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsLessThan(String value) {
			addCriterion("Administrators <", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsLessThanOrEqualTo(String value) {
			addCriterion("Administrators <=", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsLike(String value) {
			addCriterion("Administrators like", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsNotLike(String value) {
			addCriterion("Administrators not like", value, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsIn(List<String> values) {
			addCriterion("Administrators in", values, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsNotIn(List<String> values) {
			addCriterion("Administrators not in", values, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsBetween(String value1, String value2) {
			addCriterion("Administrators between", value1, value2, "administrators");
			return (Criteria) this;
		}

		public Criteria andAdministratorsNotBetween(String value1, String value2) {
			addCriterion("Administrators not between", value1, value2, "administrators");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("remarks like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("remarks not like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<String> values) {
			addCriterion("remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<String> values) {
			addCriterion("remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andLocknameIsNull() {
			addCriterion("lockname is null");
			return (Criteria) this;
		}

		public Criteria andLocknameIsNotNull() {
			addCriterion("lockname is not null");
			return (Criteria) this;
		}

		public Criteria andLocknameEqualTo(String value) {
			addCriterion("lockname =", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameNotEqualTo(String value) {
			addCriterion("lockname <>", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameGreaterThan(String value) {
			addCriterion("lockname >", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameGreaterThanOrEqualTo(String value) {
			addCriterion("lockname >=", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameLessThan(String value) {
			addCriterion("lockname <", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameLessThanOrEqualTo(String value) {
			addCriterion("lockname <=", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameLike(String value) {
			addCriterion("lockname like", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameNotLike(String value) {
			addCriterion("lockname not like", value, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameIn(List<String> values) {
			addCriterion("lockname in", values, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameNotIn(List<String> values) {
			addCriterion("lockname not in", values, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameBetween(String value1, String value2) {
			addCriterion("lockname between", value1, value2, "lockname");
			return (Criteria) this;
		}

		public Criteria andLocknameNotBetween(String value1, String value2) {
			addCriterion("lockname not between", value1, value2, "lockname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbg.generated  Mon Apr 01 18:35:06 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 01 14:13:03 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}